# Generated by Django 3.1.3 on 2020-11-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heroregister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heroname', models.CharField(max_length=100)),
                ('hero_age', models.IntegerField()),
                ('hero_email', models.EmailField(max_length=30)),
            ],
        ),
    ]
