# Generated by Django 3.1.3 on 2020-11-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tollywood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movieregister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_banner', models.CharField(max_length=50)),
                ('movie_hero', models.CharField(choices=[('Maheshbabu', 'Maheshbabu'), ('Nagarjuna', 'Nagarjuna')], max_length=40)),
            ],
        ),
    ]
