# Generated by Django 3.1.3 on 2020-11-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tollywood', '0002_movieregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userregister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=30)),
                ('mobile', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
                ('usergender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='movieregister',
            name='movie_hero',
            field=models.CharField(max_length=40),
        ),
    ]
